language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
services:
  - postgresql
# command to run tests
before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - psql -c "CREATE USER sam WITH PASSWORD 'o5EAX9BUKs7KfVtqUTEU';" -U postgres
script:
  - python manage.py collectstatic
  - python manage.py test