language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
services:
  - postgresql
# command to run tests
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test