# Generated by Django 2.2.2 on 2020-03-29 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20200329_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Last name')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Newspaper',
                'verbose_name_plural': 'Newspapers',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Subtitle')),
                ('nb_pages', models.IntegerField(blank=True, default=-1, null=True, verbose_name='Number of pages')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Author')),
                ('language', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Language')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Title')),
                ('link', models.TextField(blank=True, default='', null=True, verbose_name='Link to the article')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Author')),
                ('language', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Language')),
                ('newspaper', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Newspaper')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
