# Generated by Django 2.2.2 on 2020-03-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20200329_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationlink',
            name='Translation',
        ),
        migrations.AddField(
            model_name='translationlink',
            name='translation_item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Translation', verbose_name='Translation'),
        ),
    ]
