# Generated by Django 2.2.2 on 2020-03-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_auto_20200329_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationlink',
            name='translation_item',
        ),
        migrations.AddField(
            model_name='translationlink',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Translation'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translations',
            field=models.ManyToManyField(blank=True, null=True, through='dictionary.TranslationLink', to='dictionary.Translation'),
        ),
    ]
