# Generated by Django 2.2.2 on 2020-04-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_word_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
    ]
