# Generated by Django 2.2.2 on 2020-04-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_auto_20200419_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjective',
            name='plural',
            field=models.CharField(default='', max_length=100, verbose_name='Plural'),
        ),
        migrations.AlterField(
            model_name='expression',
            name='word',
            field=models.TextField(default='', verbose_name='Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='plural',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Plural'),
        ),
    ]
