# Generated by Django 2.2.2 on 2020-04-25 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0015_auto_20200425_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='original_word',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_word', to='dictionary.Word', verbose_name='Original name'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='translated_word',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translated_word', to='dictionary.Word', verbose_name='Translated name'),
        ),
    ]
