# Generated by Django 2.2.2 on 2020-04-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0017_auto_20200425_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='original_expression',
            new_name='original_exp',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='translated_expression',
            new_name='translated_exp',
        ),
    ]
