# Generated by Django 2.2.2 on 2020-04-26 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0020_remove_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, default='', max_length=100, null=True, verbose_name='Slug')),
                ('original_content', models.TextField(blank=True, default='', null=True, verbose_name='Original content')),
                ('translated_content', models.TextField(blank=True, default='', null=True, verbose_name='Original content')),
                ('language', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Language')),
            ],
            options={
                'verbose_name': 'Discussion',
                'verbose_name_plural': 'Discussions',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='TranslationLinkDiscussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Discussion')),
                ('item', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Translation')),
            ],
            options={
                'verbose_name': 'Translation - Discussion',
                'verbose_name_plural': 'Translations - Discussions',
            },
        ),
        migrations.AddField(
            model_name='discussion',
            name='topic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Topic'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='translations',
            field=models.ManyToManyField(blank=True, null=True, through='dictionary.TranslationLinkDiscussion', to='dictionary.Translation'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Topic'),
        ),
    ]
