# Generated by Django 2.2.2 on 2020-04-27 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0023_auto_20200427_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzitem',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 17, 8, 46, 627287), verbose_name='Date of delivery'),
        ),
    ]
