# Generated by Django 2.2.2 on 2020-04-27 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0024_auto_20200427_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzitem',
            name='slug',
            field=models.SlugField(default='', max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='slug',
            field=models.SlugField(default='', max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='quizzitem',
            name='delivered_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 27, 19, 37, 6, 441202), null=True, verbose_name='Date of delivery'),
        ),
        migrations.AlterField(
            model_name='quizzitem',
            name='delta_reply',
            field=models.FloatField(blank=True, default=-1, null=True, verbose_name='Duration reply (s)'),
        ),
        migrations.AlterField(
            model_name='quizzitem',
            name='success',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
