# Generated by Django 2.2.2 on 2020-03-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='support_ptr',
        ),
        migrations.RemoveField(
            model_name='support',
            name='language',
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='original_word',
            field=models.CharField(default='', max_length=100, verbose_name='Original word'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='translation',
            field=models.CharField(default='', max_length=100, verbose_name='Translation'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(default='', max_length=100, verbose_name='Word'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Newspaper',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
    ]
