# Generated by Django 2.2.2 on 2020-03-29 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_article_author_book_newspaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Translation', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Translation')),
                ('book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Book')),
            ],
            options={
                'verbose_name_plural': 'Translations - Books',
                'verbose_name': 'Translation - Book',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='translations',
            field=models.ManyToManyField(through='dictionary.TranslationLink', to='dictionary.Translation'),
        ),
    ]
