# Generated by Django 2.2.2 on 2020-03-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20200329_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Title'),
        ),
    ]
