# Generated by Django 2.2.2 on 2020-04-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_auto_20200412_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, null=True, verbose_name='Slug'),
        ),
    ]
