# Generated by Django 2.2.2 on 2020-04-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_remove_word_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='plural',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Plural'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='original_word',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='original_word', to='dictionary.Word', verbose_name='Original name'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='translated_word',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='translated_word', to='dictionary.Word', verbose_name='Translated name'),
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=100, verbose_name='Word')),
                ('language', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Language')),
            ],
            options={
                'verbose_name': 'Verb',
                'verbose_name_plural': 'Verbs',
            },
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=100, verbose_name='Word')),
                ('language', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Language')),
            ],
            options={
                'verbose_name': 'Expression',
                'verbose_name_plural': 'Expressions',
            },
        ),
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=100, verbose_name='Word')),
                ('plural', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Plural')),
                ('language', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Language')),
            ],
            options={
                'verbose_name': 'Adjective',
                'verbose_name_plural': 'Adjectives',
            },
        ),
        migrations.AddField(
            model_name='translation',
            name='original_adj',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_adj', to='dictionary.Adjective', verbose_name='Original adjective'),
        ),
        migrations.AddField(
            model_name='translation',
            name='original_expression',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_exp', to='dictionary.Expression', verbose_name='Original expression'),
        ),
        migrations.AddField(
            model_name='translation',
            name='original_verb',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_verb', to='dictionary.Verb', verbose_name='Original verb'),
        ),
        migrations.AddField(
            model_name='translation',
            name='translated_adj',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translated_adj', to='dictionary.Adjective', verbose_name='Translated adjective'),
        ),
        migrations.AddField(
            model_name='translation',
            name='translated_expression',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translated_exp', to='dictionary.Expression', verbose_name='Translated expression'),
        ),
        migrations.AddField(
            model_name='translation',
            name='translated_verb',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translated_verb', to='dictionary.Verb', verbose_name='Translated verb'),
        ),
    ]
