# Generated by Django 2.2.2 on 2020-04-25 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0018_auto_20200425_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationLinkArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Article')),
                ('item', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Translation')),
            ],
            options={
                'verbose_name_plural': 'Translations - Articles',
                'verbose_name': 'Translation - Article',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='translations',
            field=models.ManyToManyField(blank=True, null=True, through='dictionary.TranslationLinkArticle', to='dictionary.Translation'),
        ),
    ]
