# Generated by Django 2.2.2 on 2020-04-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0019_auto_20200425_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
