# Generated by Django 2.2.2 on 2020-04-27 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0022_auto_20200427_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='quizzitem',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 16, 21, 22, 476871), verbose_name='Date of delivery'),
        ),
    ]
