# Generated by Django 3.0.6 on 2020-06-10 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0034_auto_20200514_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='heuristic_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Heuristic score'),
        ),
        migrations.AlterField(
            model_name='quizzitem',
            name='delivered_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 10, 18, 28, 20, 487531), null=True, verbose_name='Date of delivery'),
        ),
    ]
